[alias]     # command aliases
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"

[build]
target-dir = ".cargo-artifacts"         # path of where to place all generated artifacts
rustflags = ["-C", "target-cpu=native"]        # custom flags to pass to all compiler invocations
incremental = true            # whether or not to enable incremental compilation
rustc-wrapper = "sccache"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
overflow-checks = false
debug-assertions = false
strip = "debuginfo"

[future-incompat-report]
frequency = 'always' # when to display a notification about a future incompat report

[cargo-new]
vcs = "git"              # VCS to use ('git', 'hg', 'pijul', 'fossil', 'none')

[term]
quiet = false          # whether cargo output is quiet
verbose = false        # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
